# from elasticsearch import Elasticsearch
#
# # Password for the 'elastic' user generated by Elasticsearch
# ELASTIC_PASSWORD = "WPQWdAY5ztI*ncgQCZn="
#
# # Create the client instance
# client = Elasticsearch(
#     "https://localhost:9200",
#     ca_certs="/home/zakipoint/elasticsearch-8.13.1/config/certs/http_ca.crt",
#     basic_auth=("elastic", ELASTIC_PASSWORD)
# )
#
# print(client.ping())
#
# #create index
# client.create(index='work_mock')
# #display all indices
# indices = client.indices.get_alias("*")
# for index in indices:
#     print(index)

import csv
from elasticsearch import Elasticsearch

ELASTIC_PASSWORD = "WPQWdAY5ztI*ncgQCZn="

es = Elasticsearch(
    "https://localhost:9200",
    ca_certs="/home/zakipoint/elasticsearch-8.13.1/config/certs/http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Define the index name
index_name = 'work_mock'  # Replace 'your_index_name' with your actual index name

# Define the CSV file path
csv_file_path = 'combined_data.csv'  # Replace 'your_csv_file.csv' with the actual path to your CSV file

# Open the CSV file and insert data into Elasticsearch
with open(csv_file_path, mode='r') as file:
    csv_reader = csv.DictReader(file)
    for row in csv_reader:
        # Index the document into Elasticsearch
        response = es.index(index=index_name, body=row)
        # Print the response
        print(response)
